### ISSUE TITLE
dont work not show any error

### ISSUE THREAD

**Issue by nadif15** [BlueArduino20/WiFi-Spam#5]
after start and try all option always forced exit help

**Comment by ToastiiOfficial** [comment]
You will probably need to put your wireless card into monitor mode if it supports it by doing:
airmon-ng start wlan<number of your wireless card>mon

**Comment by BlueArduino20** [comment]
Make sure that you install all the dependencies: https://github.com/BlueArduino20/WiFi-Spam#dependencies
